# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: macos-latest
    # The type of runner that the job will run on
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_13_beta.app"
    
    - name: Xcode Build
      uses: sersoft-gmbh/xcodebuild-action@v1.5.0
      with:
        project: Notificator.xcodeproj
        scheme: Notificator
        destination: platform=iOS Simulator,OS=15.0,name=iPhone 12 Pro
        action: build
